### ISSUE TITLE
Link broken 😮

### ISSUE THREAD

**Issue by Malwine** [rubymonsters/rubymonsters.github.io#6]
Hi people,
there is a link broken on your homepage: 
![screen shot 2016-03-13 at 17 37 36](https://cloud.githubusercontent.com/assets/5123681/13729989/604cfefa-e942-11e5-8b5f-be183c600246.png)
It links to `http://railsgirlsapp.shellyapp.com/` but should link to `https://rorganize.it/`
Thanks in advance for fixing it.

**Comment by svenfuchs** [comment]
Thanks for the report, @Malwine 

I've merged @til's pull request
